services:
  adminer:
    depends_on:
      - db
    build:
      context: .
      target: adminer
    container_name: adminer
    ports:
      - "8080:8080"
  api:
    build:
      target: builder
    image: busmap-api_dev
    container_name: api_dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/api:/app/packages/api
      - ./packages/common/dist:/app/packages/common/dist
    command:
      - npm
      - run
      - dev
      - -w
      - api
  ui:
    depends_on:
      - api
    build:
      context: .
      target: builder
    container_name: ui
    volumes:
      - ./packages/ui:/app/packages/ui
      - ./packages/common/dist:/app/packages/common/dist
      - ./packages/components/dist:/app/packages/components/dist
      - ./.env:/app/.env # used to inject VITE_ env vars
    ports:
      - "5173:5173"
    environment:
      API_HOST: ${API_HOST}
    command:
      - npm
      - run
      - dev
      - -w
      - ui
  storybook:
    build:
      context: .
      target: builder
    container_name: storybook
    volumes:
      - ./packages/components:/app/packages/components
    ports:
      - "9000:9000"
    command:
      - npm
      - run
      - storybook
      - -w
      - "@busmap/components"
  dev:
    depends_on:
      - ui
    build:
      context: .
      target: dev
    container_name: dev
    ports:
      - "80:80"
      - "443:443"
  stage:
    volumes:
      - ./packages/ui/dist:/var/www/${HOST_NAME}
