services:
  db:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        # Max disk usage 60MB
        max-file: 3
        max-size: 20m
  session:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        # Max disk usage 60MB
        max-file: 3
        max-size: 20m
  api:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        # Max disk usage 100MB
        max-file: 5
        max-size: 20m
    environment:
      NODE_ENV: production
      DEBUG: ""
  stage:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        # Max disk usage 100MB
        max-file: 5
        max-size: 20m
