services:
  api:
    build:
      context: .
      target: busmap
    container_name: api
    volumes:
      - .:/app
      - shared_node_modules:/app/node_modules
      - api_node_modules:/app/packages/api/node_modules
    ports:
      - "3000:3000"
    env_file: ./packages/api/.env
    entrypoint:
      - npm
      - run
      - dev
      - -w
      - api
  ui:
    depends_on:
      - api
    build:
      context: .
      target: busmap
    container_name: ui
    volumes:
      - .:/app
      - shared_node_modules:/app/node_modules
      - ui_node_modules:/app/packages/ui/node_modules
      - components_node_modules:/app/packages/components/node_modules
    ports:
      - "5173:5173"
    entrypoint:
      - npm
      - run
      - dev
      - -w
      - ui
  storybook:
    build:
      context: .
      target: busmap
    container_name: storybook
    volumes:
      - .:/app
      - shared_node_modules:/app/node_modules
      - components_node_modules:/app/packages/components/node_modules
    ports:
      - "9000:9000"
    entrypoint:
      - npm
      - run
      - storybook
      - -w
      - "@busmap/components"
  dev:
    depends_on:
      - ui
    build:
      context: .
      target: dev
    container_name: dev
    ports:
      - "80:80"
      - "443:443"
  stage:
    depends_on:
      - api
    build:
      context: .
      target: stage
    container_name: stage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./packages/ui/dist:/var/www/busmap.localhost
  web:
    depends_on:
      - api
    build:
      context: .
      target: web
    container_name: web
    ports:
      - "80:80"
      - "443:443"

volumes:
  shared_node_modules:
  api_node_modules:
  ui_node_modules:
  components_node_modules:
