name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '20.10.0'
      - name: Install Dependencies
        run: npm ci
      - name: Save error log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: npm-debug-log-${{ hashFiles('package-lock.json') }}
          path: npm-debug.log
      - name: Circular Dependencies
        run: npm run cycles
      - name: Lint
        run: npm run lint
      - name: Build Docker
        env:
          BM_COOKIE_SECRET: ${{ secrets.BM_COOKIE_SECRET }}
          BM_POSTGRES_PASSWORD: ${{ secrets.BM_POSTGRES_PASSWORD }}
          BM_POSTGRES_USER: ${{ secrets.BM_POSTGRES_USER }}
          BM_POSTGRES_DB: ${{ secrets.BM_POSTGRES_DB }}
          SSO_GOOG_CLIENT_ID: ${{ secrets.SSO_GOOG_CLIENT_ID }}
          SSO_GOOG_CLIENT_SECRET: ${{ secrets.SSO_GOOG_CLIENT_SECRET }}
        run: docker compose -f compose.yaml build stage
      - name: Build Components
        run: npm run build -w @busmap/components
      - name: Build Common
        run: npm run build -w @busmap/common
      - name: Build API
        run: npm run build -w api
      - name: Build UI
        run: npm run build -w ui
